# Generated by Django 3.0.3 on 2020-06-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ('cag_name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_img',
            field=models.ImageField(upload_to='photos/cag'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_cag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodsCategory'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.ImageField(blank=True, upload_to='photos/goods'),
        ),
    ]
