# Generated by Django 3.0.3 on 2020-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200622_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_img',
            field=models.ImageField(upload_to='goods/static/cag'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.ImageField(blank=True, upload_to='goods/static/goods'),
        ),
    ]
