# Generated by Django 3.0.3 on 2020-06-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200622_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_cag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory'),
        ),
    ]
