# Generated by Django 3.0.3 on 2020-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200622_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_img',
            field=models.ImageField(upload_to='cag'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.ImageField(blank=True, upload_to='goods'),
        ),
    ]
